name: Compilation Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compilation_check:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Roborio Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Compile code and run tests
        run: ./gradlew build -PfromCI
